### ISSUE TITLE
Flexible CUDA version based on running PC

### ISSUE THREAD

**Issue by David-OConnor** [coreylowman/cudarc#408]
Hi! I'm wondering if there is a way to make it so, if the user (PC running the program, not compiling it) has any supported version of CUDA installed, it will work? I'm working on making binaries for my program for people to download, and am not sure the best workflow. I think I'll have it so the user must have a version of CUDA installed, but would like to not hard-code which one. Thoughts on how to do this? Thank you!

For example, these are the features I use in my application, so I could make it work by distributing a binary for each CUDA version (Or if there is no CUDA version), but am wondering about a more flexible way:

```toml
[features]
default = ["cuda-12060"]

cuda = ["cuda_setup"]
cuda-12050 = ["cuda", "cudarc/cuda-12050", "lin_alg/cuda-12050"]
cuda-12060 = ["cuda", "cudarc/cuda-12060", "lin_alg/cuda-12060"]
cuda-12080 = ["cuda", "cudarc/cuda-12080", "lin_alg/cuda-12080"]
cuda-12090 = ["cuda", "cudarc/cuda-12090", "lin_alg/cuda-12090"]
```
